version: '3.8'

services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - TWITCH_BOT_USERNAME=${TWITCH_BOT_USERNAME}
      - TWITCH_OAUTH_TOKEN=${TWITCH_OAUTH_TOKEN}
      - TWITCH_CHANNEL=${TWITCH_CHANNEL}
      - PERSPECTIVE_API_KEY=${PERSPECTIVE_API_KEY}
      - TARKOV_API_URL=${TARKOV_API_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
      - postgres

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TARKOV_API_URL=${TARKOV_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data: 