# minimumReleaseAge: 64800
# Because we recently installed new dependencies, the 45-day period will prevent dependencies from being installed, and after that, this restriction will be gradually relaxed.
minimumReleaseAge: 11520
allowBuilds:
  core-js: false
  puppeteer: true
  sharp: true
  esbuild: true
  workerd: true

