apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: marksoftbot-api-pdb
  namespace: marksoftbot
  labels:
    app: marksoftbot
    component: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: marksoftbot
      component: api 