apiVersion: v1
kind: Secret
metadata:
  name: ultimate-twitch-bot-secrets
  namespace: ultimate-twitch-bot
type: Opaque
stringData:
  TWITCH_BOT_USERNAME: "your_bot_username"
  TWITCH_OAUTH_TOKEN: "oauth:your_oauth_token"
  TWITCH_CLIENT_ID: "eW91ci10d2l0Y2gtY2xpZW50LWlk"
  TWITCH_CLIENT_SECRET: "eW91ci10d2l0Y2gtY2xpZW50LXNlY3JldA=="
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "cG9zdGdyZXM="
  REDIS_PASSWORD: "cmVkaXM="
  DEEPL_API_KEY: "your_deepl_api_key"
  SPOTIFY_CLIENT_ID: "your_spotify_client_id"
  SPOTIFY_CLIENT_SECRET: "your_spotify_client_secret"
  JWT_SECRET: "eW91ci1qd3Qtc2VjcmV0"
  COOKIE_SECRET: "your_cookie_secret"
  CSRF_SECRET: "your_csrf_secret"
  SESSION_SECRET: "your_session_secret"
  CLOUDFLARE_API_KEY: "your_cloudflare_api_key"
  CLOUDFLARE_API_EMAIL: "your_cloudflare_email"
  CLOUDFLARE_ZONE_ID: "your_cloudflare_zone_id"
  AWS_ACCESS_KEY_ID: "your_aws_access_key"
  AWS_SECRET_ACCESS_KEY: "your_aws_secret_key"
  AWS_REGION: "your_aws_region"
  GCP_PROJECT_ID: "your_gcp_project_id"
  GCP_SERVICE_ACCOUNT_KEY: "your_gcp_service_account_key"
  AZURE_TENANT_ID: "your_azure_tenant_id"
  AZURE_CLIENT_ID: "your_azure_client_id"
  AZURE_CLIENT_SECRET: "your_azure_client_secret"
  AZURE_SUBSCRIPTION_ID: "your_azure_subscription_id"
  GITHUB_TOKEN: "your_github_token"
  DOCKERHUB_USERNAME: "your_dockerhub_username"
  DOCKERHUB_PASSWORD: "your_dockerhub_password"
  SLACK_WEBHOOK_URL: "your_slack_webhook_url"
  DISCORD_WEBHOOK_URL: "your_discord_webhook_url"
  TELEGRAM_BOT_TOKEN: "your_telegram_bot_token"
  TELEGRAM_CHAT_ID: "your_telegram_chat_id"
  EMAIL_SMTP_HOST: "your_smtp_host"
  EMAIL_SMTP_PORT: "your_smtp_port"
  EMAIL_SMTP_USER: "your_smtp_user"
  EMAIL_SMTP_PASSWORD: "your_smtp_password"
  EMAIL_FROM: "your_email_from"
  EMAIL_TO: "your_email_to"
  SMS_API_KEY: "your_sms_api_key"
  SMS_API_SECRET: "your_sms_api_secret"
  SMS_FROM: "your_sms_from"
  SMS_TO: "your_sms_to"
  PUSH_NOTIFICATION_API_KEY: "your_push_notification_api_key"
  PUSH_NOTIFICATION_API_SECRET: "your_push_notification_api_secret"
  PUSH_NOTIFICATION_TOPIC: "your_push_notification_topic"
  PUSH_NOTIFICATION_DEVICE_ID: "your_push_notification_device_id"
  PUSH_NOTIFICATION_PLATFORM: "your_push_notification_platform"
  PUSH_NOTIFICATION_ENVIRONMENT: "your_push_notification_environment"
  PUSH_NOTIFICATION_CERTIFICATE: "your_push_notification_certificate"
  PUSH_NOTIFICATION_PRIVATE_KEY: "your_push_notification_private_key"
  PUSH_NOTIFICATION_PASSPHRASE: "your_push_notification_passphrase"
  PUSH_NOTIFICATION_BUNDLE_ID: "your_push_notification_bundle_id"
  PUSH_NOTIFICATION_TEAM_ID: "your_push_notification_team_id"
  PUSH_NOTIFICATION_KEY_ID: "your_push_notification_key_id"
  PUSH_NOTIFICATION_APP_ID: "your_push_notification_app_id"
  PUSH_NOTIFICATION_APP_SECRET: "your_push_notification_app_secret"
  PUSH_NOTIFICATION_APP_CERTIFICATE: "your_push_notification_app_certificate"
  PUSH_NOTIFICATION_APP_PRIVATE_KEY: "your_push_notification_app_private_key"
  PUSH_NOTIFICATION_APP_PASSPHRASE: "your_push_notification_app_passphrase"
  PUSH_NOTIFICATION_APP_BUNDLE_ID: "your_push_notification_app_bundle_id"
  PUSH_NOTIFICATION_APP_TEAM_ID: "your_push_notification_app_team_id"
  PUSH_NOTIFICATION_APP_KEY_ID: "your_push_notification_app_key_id"
  PUSH_NOTIFICATION_APP_APP_ID: "your_push_notification_app_app_id"
  PUSH_NOTIFICATION_APP_APP_SECRET: "your_push_notification_app_app_secret"
  PUSH_NOTIFICATION_APP_APP_CERTIFICATE: "your_push_notification_app_app_certificate"
  PUSH_NOTIFICATION_APP_APP_PRIVATE_KEY: "your_push_notification_app_app_private_key"
  PUSH_NOTIFICATION_APP_APP_PASSPHRASE: "your_push_notification_app_app_passphrase"
  PUSH_NOTIFICATION_APP_APP_BUNDLE_ID: "your_push_notification_app_app_bundle_id"
  PUSH_NOTIFICATION_APP_APP_TEAM_ID: "your_push_notification_app_app_team_id"
  PUSH_NOTIFICATION_APP_APP_KEY_ID: "your_push_notification_app_app_app_key_id" 