name: New Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  comment:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest

    steps:
      # Comment on new PR requests with deployment instructions
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6
      - name: comment
        uses: GrantBirki/comment@3439715f0cf3b8fc29bf47be0e3226679c06c41a # pin@v3.0.0
        continue-on-error: true
        with:
          file: .github/new-pr-comment.md
