name: New Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  comment:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest

    steps:
      # Comment on new PR requests with deployment instructions
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v6
      - name: comment
        uses: GrantBirki/comment@937820f3623fd0e300294bcc64ac7577fc0ad4cc # pin@v3.0.3
        continue-on-error: true
        with:
          file: .github/new-pr-comment.md
